<?php

/**
 * Mikoa na wilaya za Tanzania (31 mikoa).
 */
return [
    'regions' => [
        'Arusha' => [
            'Arusha City',
            'Arusha',
            'Karatu',
            'Longido',
            'Meru',
            'Monduli',
            'Ngorongoro',
        ],
        'Dar es Salaam' => [
            'Ilala',
            'Kinondoni',
            'Temeke',
            'Ubungo',
            'Kigamboni',
        ],
        'Dodoma' => [
            'Bahi',
            'Chamwino',
            'Chemba',
            'Dodoma',
            'Kondoa',
            'Kongwa',
            'Mpwapwa',
        ],
        'Geita' => [
            'Bukombe',
            'Chato',
            'Geita',
            'Mbogwe',
            "Nyang'hwale",
        ],
        'Iringa' => [
            'Iringa',
            'Kilolo',
            'Mafinga',
            'Mufindi',
        ],
        'Kagera' => [
            'Biharamulo',
            'Bukoba',
            'Karagwe',
            'Kyerwa',
            'Missenyi',
            'Muleba',
            'Ngara',
        ],
        'Katavi' => [
            'Mlele',
            'Mpanda',
            'Nsimbo',
        ],
        'Kigoma' => [
            'Buhigwe',
            'Kakonko',
            'Kasulu',
            'Kibondo',
            'Kigoma',
            'Uvinza',
        ],
        'Kilimanjaro' => [
            'Hai',
            'Moshi',
            'Mwanga',
            'Rombo',
            'Same',
            'Siha',
        ],
        'Lindi' => [
            'Kilwa',
            'Lindi',
            'Liwale',
            'Nachingwea',
            'Ruangwa',
        ],
        'Manyara' => [
            'Babati',
            'Hanang',
            'Kiteto',
            'Mbulu',
            'Simanjiro',
        ],
        'Mara' => [
            'Bunda',
            'Butiama',
            'Musoma',
            'Rorya',
            'Serengeti',
            'Tarime',
        ],
        'Mbeya' => [
            'Busokelo',
            'Chunya',
            'Kyela',
            'Mbarali',
            'Mbeya',
            'Rungwe',
        ],
        'Morogoro' => [
            'Gairo',
            'Kilombero',
            'Kilosa',
            'Morogoro',
            'Mvomero',
            'Ulanga',
        ],
        'Mtwara' => [
            'Masasi',
            'Mtwara',
            'Nanyumbu',
            'Newala',
            'Tandahimba',
        ],
        'Mwanza' => [
            'Ilemela',
            'Kwimba',
            'Magu',
            'Misungwi',
            'Nyamagana',
            'Sengerema',
            'Ukerewe',
        ],
        'Njombe' => [
            'Ludewa',
            'Makete',
            'Njombe',
            "Wanging'ombe",
        ],
        'Kaskazini Pemba' => [
            'Micheweni',
            'Wete',
        ],
        'Kusini Pemba' => [
            'Chake Chake',
            'Mkoani',
        ],
        'Pwani' => [
            'Bagamoyo',
            'Kibaha',
            'Kisarawe',
            'Mafia',
            'Mkuranga',
            'Rufiji',
        ],
        'Rukwa' => [
            'Kalambo',
            'Nkasi',
            'Sumbawanga',
        ],
        'Ruvuma' => [
            'Mbinga',
            'Namtumbo',
            'Nyasa',
            'Songea',
            'Tunduru',
        ],
        'Shinyanga' => [
            'Kahama',
            'Kishapu',
            'Shinyanga',
        ],
        'Simiyu' => [
            'Bariadi',
            'Busega',
            'Itilima',
            'Maswa',
            'Meatu',
        ],
        'Singida' => [
            'Iramba',
            'Manyoni',
            'Mkalama',
            'Singida',
        ],
        'Songwe' => [
            'Ileje',
            'Mbozi',
            'Momba',
            'Songwe',
        ],
        'Tabora' => [
            'Igunga',
            'Kaliua',
            'Nzega',
            'Sikonge',
            'Tabora',
            'Urambo',
            'Uyui',
        ],
        'Tanga' => [
            'Handeni',
            'Kilindi',
            'Korogwe',
            'Lushoto',
            'Mkinga',
            'Muheza',
            'Pangani',
            'Tanga',
        ],
        'Kaskazini Unguja' => [
            'Kaskazini A',
            'Kaskazini B',
        ],
        'Kusini Unguja' => [
            'Kati',
            'Kusini',
        ],
        'Mjini Magharibi' => [
            'Magharibi',
        ],
    ],
];
